# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bootstrap Design
email: info@bootstrapdesign.ca
permalink: /:categories/:title.html
description: We provide Construction Management and General Contracting for businesses with unique projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bootstrapdesign.ca" # the base hostname & protocol for your site
twitter_username:
facebook_username:
tumblr_username:
instagram_username: bootstrapdesign
github_username:
linkedin_username:

# Build settings
markdown: kramdown
